#!/bin/bash

if [[ $# -lt 2 ]]; then
    echo "Usage: deb <package> <url>"
    echo "e.g. deb discord https://discord.com/api/download?platform=linux&format=deb" 

    exit 1
fi

PACKAGE=$1  
URL=$2                                                      

curl -L -o /tmp/$PACKAGE.deb $URL

sudo apt install /tmp/$PACKAGE.deb
